Авторизация с помощью CanCanCan
Tekkon/thinknetica pull request #11
Opened 2017-09-11 18:25 UTC by Tekkon

2017-09-11 21:30 UTC, darialapina requested changes

2017-09-11 21:30 UTC, darialapina commented on app/controllers/application_controller.rb
> +  end
Сделай обработку ошибки авторизации для всех типов запросов (html, js, json). для js и json можно возвращать 403 статус (forbidden), на клиенте его перехватывать и выводить сообщение

2017-09-11 21:30 UTC, darialapina commented on app/controllers/attachments_controller.rb
>      respond_with @attachment.destroy if is_attachmentable_author?
От проверки можно избавиться. И от сообщения выше.
Ну и от метода is_attachmentable_author? тоже.

2017-09-11 21:30 UTC, darialapina commented on app/models/ability.rb
> +    can :destroy, [Question, Answer, Comment], user: user
Можно записать сразу
`can [:update, :destroy], [Question, Answer, Comment], user: user`
и опустить :edit, так как, по-умолчанию, cancancan создаёт [алиасы](https://github.com/CanCanCommunity/cancancan/wiki/Action-Aliases). Если ты позволяешь пользователю действие update, то будет разрешено и edit (аналогично с create и new)

2017-09-11 21:30 UTC, darialapina commented on spec/models/ability_spec.rb
> +      it { should_not be_able_to :edit, create(:question, user: another_user), user: user  }
По сути, получается, что эти проверки лишние (и аналогичные им на :edit ниже).

2017-09-11 21:30 UTC, darialapina commented on spec/models/ability_spec.rb
> +      it { should_not be_able_to :mark_favorite, create(:answer, question: create(:question, user: another_user), user: user), user: user  }
в этих проверках вопрос не обязательно должен принадлежать тому же user. Если убрать этот параметр из создания читаемость немного улучшится.

2017-09-11 21:30 UTC, darialapina commented on spec/models/ability_spec.rb
> +      it { should be_able_to :destroy, create(:attachment, attachmentable: answer, file: file), user: user }
В принципе, тут, для attachment, и ниже, для голосования, достаточно выполнить проверку только для вопроса (ну или только для ответа), как ты для комментариев сделал.

2017-09-12 05:53 UTC, Tekkon commented on spec/models/ability_spec.rb
> +      it { should_not be_able_to :mark_favorite, create(:answer, question: create(:question, user: another_user), user: user), user: user  }
Нельзя убрать параметр user из создания ответа, будет ошибка "Validation failed: User must exist".

2017-09-12 05:59 UTC, darialapina commented on spec/models/ability_spec.rb
> +      it { should_not be_able_to :mark_favorite, create(:answer, question: create(:question, user: another_user), user: user), user: user  }
Лучше в фабрике указать ассоциацию, тогда какой-то пользователь будет создаваться автоматически.
http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md#Associations

2017-09-12 08:54 UTC, darialapina approved these changes

2017-09-12 09:16 UTC, merged