Feature/ajax1
Tekkon/thinknetica pull request #4
Opened 2017-08-17 12:50 UTC by Tekkon

Добавление ответов к вопросам через ajax

2017-08-17 13:38 UTC, darialapina requested changes

2017-08-17 13:38 UTC, darialapina commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render 'questions/answers' %>');
В задании сказано и выделено жирным: нужно добавлять только вновь созданный ответ к вопросу, без повторного рендеринга всего списка ответов.
У тебя же как раз весь список ответов рендерится повторно.

2017-08-17 13:38 UTC, darialapina commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render 'questions/answers' %>');
Сделай паршл answers/_answer для одного ответа, тогда 1 ответ можно будет рендерить так: `render @answer`, а коллекцию так: `render @question.answers`. В самом паршале ответ будет доступен как локальная переменная `answer`. Это т.н. анонимные паршалы.

2017-08-17 13:38 UTC, darialapina commented on app/views/questions/show.html.slim
> +  = render 'answers'
Если применить анонимные паршалы (см. выше), то весь список можно отрендерить так: render @question.answers

2017-08-17 13:47 UTC, vkurennov requested changes

2017-08-17 13:47 UTC, vkurennov commented on Gemfile
> +gem 'coffee-script-source', '1.8.0'
А зачем тебе этот гем?

2017-08-17 15:36 UTC, darialapina requested changes

2017-08-17 15:36 UTC, darialapina commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render @question.answers %>');
Здесь нужно не перерисовывать весь блок с ответами, а добавлять на страницу только новый. Теперь, когда есть паршал для ответа это сделать просто.

2017-08-17 16:37 UTC, darialapina requested changes

2017-08-17 16:37 UTC, darialapina commented on app/views/answers/create.js.erb
> +$('.answer').html('<%= j render @answer %>');
А что произойдет, если добавлять без обновления страницы два и более ответов?
Используй append() - http://api.jquery.com/append/

2017-08-18 09:56 UTC, vkurennov requested changes

2017-08-18 09:56 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  skip_before_action :verify_authenticity_token
Это еще почему вдруг? Ты же делаешь дыру в безопасности. если возникает ошибка токена, значит, что-то в форме ты сделал не так как нужно.

2017-08-18 11:17 UTC, vkurennov approved these changes

2017-08-21 15:57 UTC, merged