Feature/ajax2
Tekkon/thinknetica pull request #5
Opened 2017-08-23 18:26 UTC by Tekkon

- Только автор может отредактировать свой вопрос
  - Только автор может отредактировать свой ответ
  - Переделать удаление ответов на ajax
  - Автор вопроса может выбрать лучший ответ для своего вопроса (лучший ответ может быть только 1)
  - Автор вопроса может выбрать другой ответ как лучший, если у вопроса уже выбран лучший ответ.
  - Если у вопроса выбран лучший ответ, то он отображается первым в списке ответов.

2017-08-23 19:35 UTC, darialapina requested changes

2017-08-23 19:35 UTC, darialapina commented on app/controllers/questions_controller.rb
> +    @question.update(question_params)
Нужно еще проверить, что не-автор не может изменить вопрос

2017-08-23 19:35 UTC, darialapina commented on app/controllers/answers_controller.rb
>      @answer.update(answer_params)
Нужно еще проверить, что не-автор не может изменить ответ

2017-08-23 19:35 UTC, darialapina commented on app/controllers/answers_controller.rb
> +    if @answer.favorite
Действия редактирования и выбора лучшего ответа лучще разделить на разные action'ы в контроллере.
Редактировать ответ может автор ответа.
Выбрать лучший - автор вопроса.
Если оставить в одном методе, то придётся проверять кто какие параметры меняет, лишняя сложность.

2017-08-23 19:35 UTC, darialapina commented on app/views/answers/_answer.html.slim
> +    - if user_signed_in? && (current_user.author_of?(answer) || current_user.author_of?(answer.question))
В задании говорится:
**Только автор может отредактировать свой ответ**

2017-08-23 19:35 UTC, darialapina commented on app/views/answers/_answer.html.slim
>        = form_for [@question, answer], remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
Форма с кнопкой сохранить будет показываться всем посетителям?

2017-08-23 19:35 UTC, darialapina commented on app/views/answers/update.js.erb
> +  $('.answers').html('<%= j render @question.answers.sort_by { |a| a.favorite ? 0 : 1 } %>')
Обновлять весь список ответов - не хорошо, в прошлых заданиях такое поведение убирали.
Опять же, если разделить редактирование (вопрос останется на месте) и выбор лучшего (перенести див с ответом выше), то всё будет ок.

2017-08-23 19:35 UTC, darialapina commented on app/views/questions/_question.html.slim
> +      = form_for question, remote: true, html: {id: "edit-question-#{question.id}"} do |f|
Форма (хоть и скрытая, судя по всему) будет рендериться для всех пользователей, нужно и её за проверку на автора убрать.

2017-08-23 19:35 UTC, darialapina commented on app/views/questions/show.html.slim
> +  = render @question.answers.sort_by { |a| a.favorite ? 0 : 1 }
Ответы везде должны выводиться с лучшим наверху. Правильнее сделать default_scope в модели.

2017-08-23 19:35 UTC, darialapina commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { question_id: question, id: answer.id }, format: :js }.to change(Answer, :count).by(-1)
Тут можно проверить, что ответы уменьшились у конкретного вопроса, а не в целом в базе.

2017-08-23 19:35 UTC, darialapina commented on spec/controllers/answers_controller_spec.rb
> +    end
Нужны проверки на случай, когда не-автор пытается отредактировать ответ.

2017-08-23 19:35 UTC, darialapina commented on spec/controllers/questions_controller_spec.rb
> +    it 'assigns requested question to @question' do
Тут аналогично ответу. Нет проверок на случай запроса от не-автора вопроса.
Это в целом к блоку `describe 'PATCH #update'`. Не могу прицепить комментарий в более правильное место)

2017-08-23 19:35 UTC, darialapina commented on spec/features/create_answer_spec.rb
> +    fill_in 'create-answer-body', with: 'This is my answer.'
Так тоже можно, но рассмотри возможность ограничить поиск элемента, например, по блоку с css-классом

> within '.answers' do
>   тут действия
> end

В будущем пригодится, id не напасёшься на все элементы)

2017-08-23 19:35 UTC, darialapina commented on spec/features/create_answer_spec.rb
> +    fill_in 'create-answer-body', with: 'This is my answer.'
Собственно, ты внизу эту конструкцию используешь, тебе она знакома)

2017-08-24 07:14 UTC, vkurennov requested changes

2017-08-24 07:14 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def update
Метод должен выполнять одну задачу - либо обновлять, либо назначать ответ лучшим. У тебя в одном методе, фактически, объеденены 2.

2017-08-24 07:14 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.favorite
Во-первых, для назначения ответа лучшим и для апдейта разные проверки на автора: назначить лучшим может только автор вопроса, а редактировать свой ответ - только автор ответа.

Во-вторых, нужно выносить всю бизнес-логику из контроллера в модели. Т.е. сделать метод в модели Answer, который делает ответ лучшим, а в котнроллере просто взывать его (также в отдельном экшене)

2017-08-24 07:14 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    - if user_signed_in? && (current_user.author_of?(answer) || current_user.author_of?(answer.question))
Да, у тебя получается, что и автор вопроса может редактировать любые ответы

2017-08-24 07:14 UTC, vkurennov commented on app/views/answers/_answer.html.slim
>        = form_for [@question, answer], remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
Да, у тебя тег p в котором выводится форма (это кстати, несемантическая верстка) не вложен в if из 9-й строки.

2017-08-24 07:14 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +        - if user_signed_in? && current_user.author_of?(answer.question)
Это не нужно делать через форму. Редактирование - это одна фича, назначение лучшего - вторая

2017-08-24 07:14 UTC, vkurennov commented on app/views/answers/update.js.erb
> +  $('.answers').html('<%= j render @question.answers.sort_by { |a| a.favorite ? 0 : 1 } %>')
И сортировку делать средствами руби - очень медленно и неэффективно, используй скоуп для сортировкуи в модели и примени его здесь, у тебя сразу будут отсортированные ответы

2017-08-24 07:14 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = render @question.answers.sort_by { |a| a.favorite ? 0 : 1 }
Да, скоуп, но лучше не default_scope (у него есть определенные особенности, из-за которых не стоит его часто применять), а обычный именованый скоуп.

2017-08-24 07:14 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { question_id: question, id: answer.id }, format: :js }.to change(Answer, :count).by(-1)
На самом деле не критично :-)

2017-08-24 19:14 UTC, darialapina requested changes

2017-08-24 19:14 UTC, darialapina commented on app/models/answer.rb
> +    self.update(favorite: true)
Тут стоит применить [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарными.

2017-08-24 19:14 UTC, darialapina commented on spec/controllers/questions_controller_spec.rb
> +      expect(question.body).to include 'I really want to know!'
Ты в запросе пытаешься изменить another_question, а потом проверяешь question
Поэтому тест зеленый.
Получилось, что у ты в этом тесте залогинен под автором another_question ( он же автор question)

2017-08-25 07:50 UTC, vkurennov requested changes

2017-08-25 07:50 UTC, vkurennov commented on app/models/answer.rb
> +      self.question.unmark_favorites(self)
Вот это не стоило выносить в метод, можно было бы все прямо здесь сделать. Ну и нужно наоборот сделать - сначала убрать флаг лучшего ответа с других, а затем - сделать `update!` для текущего ответа

2017-08-25 07:50 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +              url: "/questions/#{@question.id}/answers/#{answer.id}/mark-favorite" }
Так, а почему url-хелперы не используешь? Посмотри на rake routes и используй нужный метод.

2017-08-25 07:50 UTC, vkurennov commented on app/views/questions/_question.html.slim
> +      = form_for question, remote: true, html: {id: "edit-question-#{question.id}"} do |f|
Не исправлено, форма действительно не под условием, надо сдвинуть все вместе с тегом p под условие из 5-й строки

2017-08-25 07:50 UTC, vkurennov commented on config/routes.rb
> +      put '/mark-favorite' => 'answers#mark_favorite'
Кастомные экшены в ресурсах принято писать так:

`put :mark_favorite, on: :member`

Твой синтаксис используется только если задается роут вне ресурса.

2017-08-25 07:50 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.favorite).to eq true
Нужно еще проверить, что другие лучшие ответы стали обычными. Отдельным тестом. Проверить именно то, что это происходит при вызове mark_favorite

2017-08-25 10:13 UTC, vkurennov approved these changes

2017-08-25 10:44 UTC, merged